version: "3.4"

services:

    mc-localnode:
        image: chronacle.azurecr.io/mc-localnode-sandbox:latest
        build:
            context: ../C8c.Gallery.Testnet/mc-localnode
            dockerfile: Dockerfile.mc-localnode
        container_name: mc-localnode-sandbox
        environment:
            - MC_CHAIN_NAME=c8c-sandbox
            - MC_NETWORK_PORT=12020 # MultiChain API port number
            - MC_RPC_USER=${MC_RPC_USER} # Uncomment this to provide own RPC username
            - MC_RPC_PASSWORD=${MC_RPC_PASSWORD} # Uncomment this to provide own RPC password
            - MC_RPC_ALLOWIP=${MC_RPC_ALLOWIP} # Uncomment only for development only
            - MC_SEED_IP=mc-seednode # ChronAcle Network seednode
            - MC_EXPLORER_PORT=12029 # MultiChain Exporer port number
            - BlocksQuiet=true # Do not log block notifications to console

            # Configure notification for Local API port (12038)
            - ReceivingBlockNotify=http://c8c-gallery-local-api:12038/api/v1/block # Send block notifications to LocalApi
            - ReceivingHost=http://c8c-gallery-local-api:12038/api/v1/transaction # Send txn notifications to LocalApi

            - MC_PTEKEY=${MC_PTEKEY} # Uncomment to use backup private key
        networks:
            c8c-network:
                ipv4_address: 172.111.0.99
        ports:
            - "12030:12020" # Used for network
            - "12031:12021" # Used for rpc
            - "12039:12029" # Used for explorer

    c8c-gallery-local-api:
        image: chronacle.azurecr.io/c8c-gallery-local-api:latest
        container_name: c8c-gallery-local-api
        environment:
            # ASPNET CONFIG
            - ASPNETCORE_ENVIRONMENT=sandbox
            - ASPNETCORE_URLS=http://+:12038

            # GALLERY CONFIG
            - GALLERY_AllowedOrigins=http://localhost:3000,http://127.0.0.1:3000,http://host.docker.internal:3000,https://dev.gallery.chronacle.io

            # MC CONFIG
            - GALLERY_MultiChainConfiguration__Node__NetworkAddress=172.111.0.99
            - GALLERY_MultiChainConfiguration__Node__NetworkPort=12021
            - GALLERY_MultiChainConfiguration__Node__RpcUserName=${MC_RPC_USER} # To be configured by user
            - GALLERY_MultiChainConfiguration__Node__RpcPassword=${MC_RPC_PASSWORD} # To be configured by user

            - GALLERY_ResourceServer=http://chronnet-admin-api:13000
            - GALLERY_AuthorizationServer__Authority=https://c8c-identity

        ports:
            - "12038:12038"
        networks:
            c8c-network:
                ipv4_address: 172.111.0.100

networks:
    c8c-network:
        external: true
        name: "c8c-sandbox"
